version: "3.8"
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata: